name: mikes_mindmaps
description: A collaborative mind map tool
dependencies:
  browser: any
  http_server: any
  route: any
  redis_client:
    git:
      url: git://github.com/mbirtwell/redis_client.git
dev_dependancies:
  unittest: any
  mock: any
