name: play1
description: A sample web application
dependencies:
  browser: any
  http_server: any
  route: any
  unittest: any
  mock: any
  redis_client:
    git:
      url: git://github.com/mbirtwell/redis_client.git